### ISSUE TITLE
jQuery UI v1.13.0

### ISSUE THREAD

**Issue by philwareham** [sschadwick/jquery-ui-dist#1]
Hi.

We use this repo to install jQuery UI via NPM, since the main project stubbornly refuses to include a compiled script in their repo.

Any chance you could bump it to v1.13.0 that came out a few weeks back?

Cheers,
Phil

**Comment by sschadwick** [comment]
Updated and published.

**Comment by philwareham** [comment]
Great, thanks! All working.
